**1.Create an array of 10 integers and print it.**

In [68]:
import numpy as np

In [72]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(type(arr))

<class 'numpy.ndarray'>


**2. Find the length of an array.**

In [76]:
print(len(arr))

10


**3. Print the first element of an array.**

In [81]:
print(arr[0])

1


**4.Print the last element of an array.**

In [94]:
print(arr[-1])

10


**5.Print all elements of an array using a loop.**

In [99]:
for i in arr:
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 

**6.Find the sum of all elements in an array.**

In [102]:
print(sum(arr))

55


**7.Find the maximum element in an array.**

In [105]:
print(max(arr))

10


**8.Find the minimum element in an array.**

In [108]:
print(min(arr))

1


**9.Count how many even numbers are present in an array.**

In [119]:
even_num = []
for i in arr:
    if i % 2 == 0:
        even_num.append(i)

print(len(even_num))

5


**10. Count how many odd numbers are present in an array.**

In [122]:
odd_num = []
for i in arr:
    if i % 2 != 0:
        odd_num.append(i)

print(len(odd_num))

5


**11. Reverse an array without using built-in reverse functions.**

In [125]:
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


**12. Check whether a given number exists in the array.**

In [138]:
num = int(input('Enter your number:'))

for i in arr:
    if i == num:
        print('Yes, given number exists in array')
        break
else:
    print('Sorry, given number does not exist in array')

Enter your number: 99


Sorry, given number does not exist in array


**13.Replace all negative numbers in an array with 0.**

In [141]:
arr2 = np.array([-9,4,-22,45,21,72,-12,5])

arr2[arr2 < 0] = 0
print(arr2)

[ 0  4  0 45 21 72  0  5]


**14. Find the average (mean) of array elements.**

In [147]:
print(arr2.mean())

18.375


**15. Find the second largest element in an array.**

In [172]:
arr2.sort()
print(arr2[-2])

45


**16. Remove duplicate elements from an array.**

In [185]:
arr3 = np.array([2,3,2,44,3,6,7,44,7,23,2])
print(np.unique(arr3))

[ 2  3  6  7 23 44]


**17. Find the frequency of each element in an array.**

In [200]:
arr3 = np.array([2,3,2,44,3,6,7,44,7,23,2])
(unique, counts) = np.unique(arr3, return_counts=True)
freq = dict(zip(unique, counts))
print(freq)

{2: 3, 3: 2, 6: 1, 7: 2, 23: 1, 44: 2}


**18. Merge two arrays into one.**

In [202]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
merged = np.concatenate((arr1, arr2))
print(merged)

[1 2 3 4 5 6]


**19. Sort an array in ascending order (without using built-in sort)**

In [206]:
arr4 = np.array([5,2,9,1,7])
# Simple Bubble Sort
for i in range(len(arr4)):
    for j in range(0, len(arr4)-i-1):
        if arr4[j] > arr4[j+1]:
            arr4[j], arr4[j+1] = arr4[j+1], arr4[j]

print(arr4)

[1 2 5 7 9]


**20. Rotate an array to the right by 1 position**

In [210]:
arr5 = np.array([1,2,3,4,5])
rotated = np.empty_like(arr5)
rotated[0] = arr5[-1]
rotated[1:] = arr5[:-1]
print(rotated)

[5 1 2 3 4]
